# Exercise 3: Numpy

Perform the follwing tasks:

In [21]:
#3.1: import the numpy library
import numpy as np

In [34]:
#3.2: create a random 10x10 array named A
A = np.random.randint(50, size=(10,10))
print(A)

[[25 13 47  6 44 29 29  4 35 49]
 [ 7 18  2 15  4 19  8 47  2 16]
 [23  8 18 44 49  3 21 33 40 27]
 [43 43 43 10 34 32 20 22 34 28]
 [34 47 31 45 28 10 46 30 20 14]
 [32  9 18 37 12 24  3 16 29 49]
 [37 11 14  3 28 11 26 29 16 39]
 [16 39 31 48 20 48 12 43 23 24]
 [10 47 20 49 47 10 42  4  1 37]
 [15  3 24 21 10 41  7 10 24 28]]

In [37]:
#3.3: return only the odd rows of A
print(A[:,0::2])

[[25 47 44 29 35]
 [ 7  2  4  8  2]
 [23 18 49 21 40]
 [43 43 34 20 34]
 [34 31 28 46 20]
 [32 18 12  3 29]
 [37 14 28 26 16]
 [16 31 20 12 23]
 [10 20 47 42  1]
 [15 24 10  7 24]]

In [67]:
#3.4: perform a matrix multiplication of A with it's transposed
print(A.T*A)

[[ 625   91 1081  258 1496  928 1073   64  350  735]
 [  91  324   16  645  188  171   88 1833   94   48]
 [1081   16  324 1892 1519   54  294 1023  800  648]
 [ 258  645 1892  100 1530 1184   60 1056 1666  588]
 [1496  188 1519 1530  784  120 1288  600  940  140]
 [ 928  171   54 1184  120  576   33  768  290 2009]
 [1073   88  294   60 1288   33  676  348  672  273]
 [  64 1833 1023 1056  600  768  348 1849   92  240]
 [ 350   94  800 1666  940  290  672   92    1  888]
 [ 735   48  648  588  140 2009  273  240  888  784]]

In [51]:
#3.5: compute the matrix inverse of A
print(np.linalg.inv(A))

[[-0.01855243 -0.08255187 -0.01259141 -0.02029284 -0.002415   -0.00180766
   0.07595761  0.07171698 -0.01509928 -0.03087247]
 [-0.01450206  0.07595965  0.00738202  0.05723188 -0.00036848  0.00986675
  -0.06838764 -0.08443849  0.02487697  0.03529719]
 [ 0.06147437 -0.11054749 -0.03371693 -0.07956883  0.00960016  0.00892251
   0.0724318   0.15660924 -0.04625315 -0.12674646]
 [-0.0004495  -0.04700281 -0.00345605 -0.03097816  0.00420296  0.00670679
   0.02720656  0.05279745 -0.00696105 -0.02583351]
 [-0.00828593 -0.0543051   0.00934135 -0.00950668 -0.02664307 -0.02272641
   0.04894655  0.0568571   0.00403266 -0.02311552]
 [-0.02700583  0.00633172  0.00298303  0.01719747 -0.01075243 -0.02215008
   0.00440969 -0.01763341  0.01365431  0.05863605]
 [-0.00683131  0.06408573  0.00714639  0.01722456  0.02618304 -0.01293966
  -0.04021084 -0.08840115  0.01476911  0.07303558]
 [ 0.01424389 -0.00399925 -0.00164373 -0.0198536   0.00140859 -0.00139424
   0.01804188  0.03428995 -0.0156565  -0.03329946]
 [-0.01997167  0.14316222  0.03893605  0.08472335  0.0131568   0.00912211
  -0.12970311 -0.18108748  0.02519237  0.11091833]
 [ 0.01538021  0.03891241 -0.00483078  0.00455229 -0.00311377  0.0236978
  -0.02500834 -0.03262145  0.00916168 -0.00255726]]

In [50]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )

In [76]:
print(np.where(A<20, A, A/2))

[[12.5 13.  23.5  6.  22.  14.5 14.5  4.  17.5 24.5]
 [ 7.  18.   2.  15.   4.  19.   8.  23.5  2.  16. ]
 [11.5  8.  18.  22.  24.5  3.  10.5 16.5 20.  13.5]
 [21.5 21.5 21.5 10.  17.  16.  10.  11.  17.  14. ]
 [17.  23.5 15.5 22.5 14.  10.  23.  15.  10.  14. ]
 [16.   9.  18.  18.5 12.  12.   3.  16.  14.5 24.5]
 [18.5 11.  14.   3.  14.  11.  13.  14.5 16.  19.5]
 [16.  19.5 15.5 24.  10.  24.  12.  21.5 11.5 12. ]
 [10.  23.5 10.  24.5 23.5 10.  21.   4.   1.  18.5]
 [15.   3.  12.  10.5 10.  20.5  7.  10.  12.  14. ]]